# Generated by Django 3.0.6 on 2020-05-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20200522_1754'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkheresybase',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='game.DarkHeresyGame'),
        ),
        migrations.AlterField(
            model_name='darkheresybase',
            name='die_roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='die_rolls', to='game.DarkDieRoll'),
        ),
    ]
