# Generated by Django 3.0.6 on 2020-05-22 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_darkdieroll'),
        ('world', '0002_darkheresybase_current_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkheresybase',
            name='die_roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='die_rolls', to='game.DarkDieRoll'),
        ),
    ]
