# Generated by Django 3.0.6 on 2020-06-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_darkdieroll_fate_points'),
        ('world', '0003_auto_20200526_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkheresybase',
            name='current_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to='game.DarkHeresyGame'),
        ),
        migrations.AlterField(
            model_name='darkheresybase',
            name='die_roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='die_rolls', to='game.DarkDieRoll'),
        ),
    ]
