# Generated by Django 3.0.6 on 2020-06-05 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20200602_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkheresybase',
            name='current_fate_points',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
