# Generated by Django 3.0.6 on 2020-05-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkheresygame',
            name='ready_state',
            field=models.BooleanField(default=False),
        ),
    ]
