# Generated by Django 3.0.6 on 2020-05-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0003_auto_20200522_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkheresygame',
            name='dm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
