# Generated by Django 3.0.6 on 2020-05-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_darkdieroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkdieroll',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
