# Generated by Django 3.0.6 on 2020-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_darkdieroll_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='darkdieroll',
            name='mod',
            field=models.IntegerField(default=0),
        ),
    ]
