# Generated by Django 3.0.6 on 2020-06-16 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_darkdieroll_mod'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkCombat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('combat_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_game_combats', to='game.DarkHeresyGame')),
            ],
        ),
        migrations.CreateModel(
            name='DarkCombatant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combatant_id', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('initiative', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('combat_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combantants', to='game.DarkCombat')),
            ],
        ),
    ]
