# Generated by Django 3.0.6 on 2020-06-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_darkcombat_darkcombatant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darkcombatant',
            name='combat_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combatants', to='game.DarkCombat'),
        ),
    ]
